name: qr_code_tools
description: The Flutter plugin for iOS and Android to decoding QR codes.
version: 1.0.0
homepage: https://github.com/medyas/qr_code_tools

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aifeii.qrcode.tools
        pluginClass: QrCodeToolsPlugin
      ios:
        pluginClass: QrCodeToolsPlugin

